# Generated by Django 4.1.1 on 2022-10-05 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Товар')),
                ('description', models.TextField(verbose_name='Описание')),
                ('article', models.CharField(max_length=11, verbose_name='Артикуль')),
                ('price', models.DecimalField(decimal_places=2, help_text='указывать в рублях', max_digits=19, verbose_name='Цена')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество товаров')),
                ('event', models.BooleanField(verbose_name='Акция')),
                ('percentage_event', models.IntegerField(verbose_name='Процент акции')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата появления товара')),
                ('popular', models.BooleanField(verbose_name='Популярное')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.brand')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.EmailField(blank=True, max_length=50, verbose_name='Логин через Email')),
                ('login_tel', models.CharField(blank=True, max_length=50, verbose_name='Логин через телефон')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.rating'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.subcategory'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество товаров')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена товара')),
                ('sum', models.PositiveBigIntegerField(default=0, verbose_name='Сумма цены товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
