# Generated by Django 4.1.1 on 2022-10-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crate',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
