# Generated by Django 4.1.1 on 2022-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0003_alter_products_percentage_event_alter_products_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percentage_event',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент акции'),
        ),
    ]
