# Generated by Django 4.1.1 on 2022-10-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0005_alter_products_brand_alter_products_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='amount',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Товар'),
        ),
    ]
