# Generated by Django 4.1.1 on 2022-10-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0006_rename_date_products_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
