# Generated by Django 4.1.1 on 2022-10-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0007_products_available_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='img',
            field=models.ImageField(default=0, upload_to='stars/', verbose_name='Изображение кол-ва звёзд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santehcom.brand'),
        ),
    ]
