# Generated by Django 4.1.1 on 2022-10-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0010_alter_products_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, upload_to='category/', verbose_name='Изображение, представляющее категорию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santehcom.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='santehcom.rating', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.score', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santehcom.category', verbose_name='Категория'),
        ),
    ]
