# Generated by Django 4.1.1 on 2022-10-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0011_category_image_alter_crate_product_alter_crate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='santehcom.rating', verbose_name='Оценка'),
        ),
    ]
