# Generated by Django 4.1.1 on 2022-10-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santehcom', '0014_alter_products_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
